name: PluginName
version: ${project.version}
main: cz.devfire.pluginname.PluginCore
load: POSTWORLD

# Plugin information
author: "Firestone82"
api-version: 1.13

# Other plugins depend
softdepend:
  - "PlaceholderAPI"
depend:
  - "FireLibs"
loadbefore: [ ]

# Plugin commands
commands: { }
